In [2]:
import numpy as np

In [3]:

CURVE_CENTER = 80
grades = np.array([72, 35, 64, 88, 51, 90, 74, 12])
def curve(grades):
    average = grades.mean()
    change = CURVE_CENTER - average
    new_grades = grades + change
    return np.clip(new_grades, grades, 100)

In [4]:
curve(grades)

array([ 91.25,  54.25,  83.25, 100.  ,  70.25, 100.  ,  93.25,  31.25])

In [5]:
grades.shape

(8,)

In [8]:
from numpy import reshape


temp = np.array([
    29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
    12.6, 49.9, 31.3, 9.2, 22.2, 38.4
]).reshape(2, 2, 3)
temp.shape

(2, 2, 3)

In [9]:
temp

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 31.3],
        [ 9.2, 22.2, 38.4]]])

In [10]:
np.swapaxes(temp, 1, 2)

array([[[29.3, 16.1],
        [42.1, 38. ],
        [18.8, 12.5]],

       [[12.6,  9.2],
        [49.9, 22.2],
        [31.3, 38.4]]])

In [11]:
# axes
table = np.array([
    [5, 3, 7, 1],
    [2, 6, 7, 9],
    [1, 1, 1, 1],
    [4, 3, 2, 0]
])
table.max()

9

In [12]:
table.max(axis = 0)

array([5, 6, 7, 9])

In [14]:
table.min()

0

In [16]:
table.max(axis=1)

array([7, 9, 1, 4])

In [18]:
a = np.arange(32).reshape(4, 1, 8)
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [20]:
b = np.arange(48).reshape(1, 6, 8)
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])

In [21]:
a + b

array([[[ 0,  2,  4,  6,  8, 10, 12, 14],
        [ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54]],

       [[ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62]],

       [[16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70]],

       [[24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70],
        [64, 66, 68, 70, 72,

Data Science Operations: Filter, ORder Aggregate

In [ ]:
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8]
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])

for i in range(4):
    assert square[:, i].sum() == 34
    assert square[i, :].sum == 34

assert square[:2, :2].sum() == 34
assert square[2:, :2].sum() == 34
assert square[:2, 2:].sum() == 34
assert square[2:, 2:].sum() == 34


In [25]:
# Masking and filtering
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)
numbers

array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [26]:
mask = numbers % 4 == 0
mask

array([[False, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [27]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [28]:
# Transposing, Sorting and concatenating
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [29]:
a.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [30]:
c = np.array([
    [7, 1, 4],
    [8, 6, 5],
    [1, 3, 2]
])
np.sort(c)

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [31]:
np.sort(c, axis=None)

array([1, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
# Conatenation
d = np.array([
    [4, 8],
    [6, 1],
])
x = np.array([
    [3, 5],
    [7, 2]
])

# horizontal
np.hstack((d, x))

array([[4, 8, 3, 5],
       [6, 1, 7, 2]])

In [37]:
# vertical
np.vstack((x, d))

array([[3, 5],
       [7, 2],
       [4, 8],
       [6, 1]])

take tuple of array as their arguments

In [38]:
np.concatenate((x, d))

array([[3, 5],
       [7, 2],
       [4, 8],
       [6, 1]])

In [39]:
np.concatenate((d, x), axis=None)

array([4, 8, 6, 1, 3, 5, 7, 2])

In [ ]:
# Aggregating
# eg .sum(), .max(), .mean(), .std()

In [40]:
# Maclaurin series
from math import e, factorial

fac = np.vectorize(factorial)
def e_x(x, terms = 10):
    n = np.arange(terms)
    return np.sum((x ** n) / fac(n))

if __name__ == "__main__":
    print("Actual:", e ** 3)
    print("N (terms)\tMaclaurin\tError")

    for n in range(1, 14):
        maclaurin = e_x(3, terms=n)
        print(f"{n}\t\t{maclaurin:.03f}\t\t{e**3 - maclaurin:.03f}")


Actual: 20.085536923187664
N (terms)	Maclaurin	Error
1		1.000		19.086
2		4.000		16.086
3		8.500		11.586
4		13.000		7.086
5		16.375		3.711
6		18.400		1.686
7		19.412		0.673
8		19.846		0.239
9		20.009		0.076
10		20.063		0.022
11		20.080		0.006
12		20.084		0.001
13		20.085		0.000


Numerical data types

In [42]:
a = np.array([1, 3, 5.5, 7.7, 9.2], dtype=np.single)
a

array([1. , 3. , 5.5, 7.7, 9.2], dtype=float32)

In [43]:
b = np.array([1, 3, 5.5, 7.7, 9.2], dtype=np.uint8)
b

array([1, 3, 5, 7, 9], dtype=uint8)

In [44]:
# Matplotlib
import matplotlib.image as mpimg

img = mpimg.imread("download.webp")
print(type(img))
print(img)

<class 'numpy.ndarray'>
[[[ 90 127  39]
  [ 90 127  39]
  [ 90 127  39]
  ...
  [156 170 126]
  [157 171 128]
  [159 170 128]]

 [[ 88 125  37]
  [ 88 125  37]
  [ 88 125  37]
  ...
  [158 172 129]
  [159 173 130]
  [161 172 130]]

 [[ 85 122  35]
  [ 85 122  35]
  [ 85 122  35]
  ...
  [158 172 129]
  [158 172 129]
  [161 172 130]]

 ...

 [[150 177 138]
  [147 174 136]
  [144 173 133]
  ...
  [ 81 119  67]
  [104 141  94]
  [124 164 116]]

 [[145 174 134]
  [142 172 132]
  [138 170 130]
  ...
  [ 89 126  77]
  [110 146 102]
  [128 167 120]]

 [[140 174 135]
  [138 172 133]
  [137 171 130]
  ...
  [ 92 129  83]
  [111 147 105]
  [127 166 121]]]


In [47]:
output = img.copy()
output[:, :, :2] = 0
mpimg.imsave("blue.jpg", output)

In [ ]:
average = img.mean(axis=2)
mpimg.imsave("bad-gray.jpg", average, cmap = "gray")

In [48]:
weights = np.array([0.3, 0.59, 0.11])
grayscale = img @ weights
mpimg.imsave("good-gray.jpg", grayscale, cmap="gray")